
import com.formdev.flatlaf.intellijthemes.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author SPRITE
 */
public class popup extends javax.swing.JFrame {
    
    /**
     * Creates new form popup
     */
    public popup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idCrsYrLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idNumLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idNameLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Student Info");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, 40));

        idCrsYrLabel.setBackground(new java.awt.Color(255, 255, 255));
        idCrsYrLabel.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        idCrsYrLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(idCrsYrLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 200, 20));

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel3.setText("Course & Yr :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 90, 20));

        jLabel4.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel4.setText("ID # :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 40, 20));

        idNumLabel1.setBackground(new java.awt.Color(255, 255, 255));
        idNumLabel1.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        idNumLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(idNumLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 200, 20));

        jLabel5.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        jLabel5.setText("Name :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 50, 20));

        idNameLabel1.setBackground(new java.awt.Color(255, 255, 255));
        idNameLabel1.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        idNameLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(idNameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 200, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         try {
            FlatGrayIJTheme.setup();
        } catch (Exception e) {
            e.printStackTrace();
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new popup().setVisible(true);
            }
        });
    }

    public void setLblEntries(String stud_ID, String stud_Name, String stud_Crs, String stud_Yr){
        idNumLabel1.setText(stud_ID);
        idNameLabel1.setText(stud_Name);
        idCrsYrLabel.setText(stud_Crs + " - " + stud_Yr);
    }
    
    public void timerDispose(){
        int delay = 5000;
        Timer timer = new Timer( delay, new ActionListener(){
            
            @Override
            public void actionPerformed( ActionEvent e ){
                dispose();
            }
        });
        timer.setRepeats(false);
        timer.start();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel idCrsYrLabel;
    private javax.swing.JLabel idNameLabel1;
    private javax.swing.JLabel idNumLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
